language: node_js
node_js:
  - 10.15.3
cache:
  directories:
  - node_modules
env:
  global:
    - CC_TEST_REPORTER_ID=4f744e277420809847dd884b616a8f8274b0ead30e537c6b80b2da1adc76aace
before_script:
  - export CC_TEST_REPORTER_ID=4f744e277420809847dd884b616a8f8274b0ead30e537c6b80b2da1adc76aace
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test -- --coverage -u
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
